#!/usr/bin/env ruby
#
# Demonstration of Slabot API
#   https://github.com/emmadev/sysutils/Slabot
#     -- @robzr 3/2016

require 'optparse'
require_relative 'slabot'

channels = []
slabot_options = { }

OptionParser.new do |opts|
  program_name = $PROGRAM_NAME.sub(%r{.*/}, '')
  opts.banner = "Usage: #{program_name} [-c channel [-c ...]] [-r regex [-r ...]] [-h] -s token\n\n"

  opts.on('-c', '--channel', '=MANDATORY', 'Provide a channel name to monitor')     { |arg| channels << arg }
  opts.on('-r', '--channel-regex', '=MANDATORY', 'Regex pattern to match channels') { |arg| channels << %r{#{arg}} }
  opts.on('-h', '--help', 'Display this help.')                                     { abort opts.help }
  opts.on('-s', '--slack-token', '=MANDATORY', 'Specify the Slack API token')       { |arg| slabot_options[:slack_token] = arg }
end.parse!

abort 'No Slack token specified - use -h for help' unless slabot_options[:slack_token]

slabot = Slabot::Slabot.new slabot_options.merge({ channels: channels })

# Display details about the slack connection and bot state
puts "Logged into Slack as #{slabot.slack['user']} in team #{slabot.slack['team']} (#{slabot.slack['url']})"
puts "All available channels\n -> #{slabot.channels.join("\n -> ")}"
puts "All users\n -> #{slabot.users.join("\n -> ")}"
puts "Subscribed channels\n -> #{slabot.channels(:subscribed).join("\n -> ")}"

# Most simple incantation
slabot << Slabot::Trigger.new(conditions: 'hello slabot', callback: 'Hello, my friend')

# Using a regex condition and an inline proc callback
slabot << Slabot::Trigger.new(conditions: /(who|how) are you, slabot/, callback: proc { |arg| "I\'m here and I\'m fine, #{arg[:user]}" })

# More complex Trigger, using externally declared procs for both conditions and a trigger
i_was_triggered = proc do |arg|
  "*Matched _Text* from_ ~#{arg[:user]}~ in ##{arg[:channel]}\n>>>#{arg[:text]}"
end

conditions = [
  proc do |arg|
    arg[:channel] == 'general' && arg[:text].length < 15 && arg[:text] =~ /^slabot short/i
  end,
  proc do |arg|
  arg[:channel] == 'general' && arg[:text].length > 15 && arg[:text] =~ /^slabot long/i
  end
]

slabot << Slabot::Trigger.new(conditions: conditions, callback: i_was_triggered)

puts "Defined #{slabot.triggers.length} triggers"

slabot.run
