require_relative 'instant_slack_bot/defaults'
require_relative 'instant_slack_bot/auto_loader'
require_relative 'instant_slack_bot/bot'
require_relative 'instant_slack_bot/callback'
require_relative 'instant_slack_bot/master'
require_relative 'instant_slack_bot/slack_rtm'
