#!/usr/bin/env ruby
#
# Run this in the examples directory, it will monitor the auto-loader-test directory for new modules

require_relative '../instant_slack_bot'

master = InstantSlackBot::Master.new(token: ENV['SLACK_TOKEN'])

auto_loader = InstantSlackBot::AutoLoader.new(debug: true, directory: 'auto-loader-dir', master: master)

master.run
