#!/usr/bin/env ruby
#
# InstantSlackBot Class based example
#   http://github.com/robzr/instant-slack-bot

require_relative '../instant_slack_bot'

instabot_options = { 
  options: {
    debug: false,
    use_api: :rtm
  }
}

class MyBot < InstantSlackBot::Bot
  def conditions(message: message)
    message['channel'] =~ /^bot_heaven/ ||
      message['text'] =~ /^test / ||
      message['username'] =~ /^rex/
  end

  def action(message: message)
    printf(
      "*I am responding* _to_ @%s in channel #%s\n",
      message['username'],
      message['channelname']
    )
  end
end

master = InstantSlackBot::Master.new(instabot_options)
master << MyBot.new
master.run
