#!/usr/bin/env ruby
#
# InstantSlackBot Class based example
#   http://github.com/robzr/instant-slack-bot
#
require 'pp'
require_relative '../instant_slack_bot'

instabot_options = { 
  token: ENV['SLACK_TOKEN'],
  options: {
    debug: false,
    use_api: :rtm
  },
}

class MyBot < InstantSlackBot::Bot
  def conditions(message: message)
    return true if message['channel'] =~ /^bot_heaven/
    return true if message['text'] =~ /^test /
    return true if message['username'] =~ /^rex/
    false
  end

  def action(message: message)
    "*I am responding* _to_ @#{message['username']} in channel ##{message['channelname']}\n"
  end
end

master = InstantSlackBot::Master.new(instabot_options)
master << MyBot.new
master.run
