#!/usr/bin/env ruby
#
# Demonstration of InstantSlackBot API with command line interaction
# 
#   http://github.com/robzr/instant-slack-bot
#
#     -- @robzr 3/2016
#
require_relative '../instant_slack_bot'

master = InstantSlackBot::Master.new(token: ENV['SLACK_TOKEN'])

# Display a few details about the Slack connection
puts \
  "Logged into Slack as #{master.slack_connection['user']}\n" +
  "Using team #{master.slack_connection['team']} " +
  "(#{master.slack_connection['url']})\n" +
  "All users\n -> #{master.users.join("\n -> ")}\n" +
  "Available channels\n -> #{master.channels(:available).join("\n -> ")}" +
  "Subscribed channels\n -> #{master.channels(:subscribed).join("\n -> ")}"

# Static text trigger and response
simple_bot = InstantSlackBot::Bot.new(
  conditions: 'hello instabot', 
  action: 'Hello, my friend.'
)

# Register the bot with the master
master << simple_bot

# Add another bot using a Regex condition and an inline proc action
master << InstantSlackBot::Bot.new(
  conditions: /(who|how) are you, instabot/, 
  action: proc { |message| "I\'m here and I\'m fine, @#{message['username']}." }
)

# Lambda based condition array and action
conditions = [
  lambda { |message|
    message['channelname'] == 'general' && 
      message['text'].length < 15 &&
      message['text'] =~ /^instabot short/i
  },
  lambda { |message|
    message['channelname'] == 'general' &&
      message['text'].length > 15 &&
      message['text'] =~ /^instabot long/i
  }
]
action = lambda do |message|
  printf(
    "*Matched _Text* from_ ~%s~ in #%s\n>>>%s",
    message['username'],
    message['channelname'],
    message['text']
  )
end

master << InstantSlackBot::Bot.new(conditions: conditions, action: action)

puts "Running #{master.bots.length} bots"

master.run
