#!/usr/bin/env ruby
#
# InstantSlackBot Method based example
#   http://github.com/robzr/instant-slack-bot
#
require_relative '../instant_slack_bot'

instabot_options = { 
  token: ENV['SLACK_TOKEN'],
  options: {
    debug: false,
    post_options: {
      'icon_emoji' => ':squirrel:'
    }
  }
}

def conditions(message: message)
  message['channel'] =~ /^bot_heaven/ ||
    message['text'] =~ /^test / ||
    message['username'] =~ /^rex/
end

def action(message: message)
  printf(
    "*I am responding* _to_ @%s in channel #%s\n",
    message['username'],
    message['channelname']
  )
end

master = InstantSlackBot::Master.new instabot_options

master << InstantSlackBot::Bot.new(
  conditions: method(:conditions),
  action: method(:action)
)

master.run
