#!/usr/bin/env ruby
#
# InstantSlackBot Method based example
#   http://github.com/robzr/instant-slack-bot
#
require_relative '../instant_slack_bot'

instabot_options = { 
  token: ENV['SLACK_TOKEN'],
  options: {
    debug: false,
    post_options: {
      'icon_emoji' => ':squirrel:'
    }
  }
}

def conditions(message: message)
  return true if message['channel'] =~ /^bot_heaven/
  return true if message['text'] =~ /^test /
  return true if message['username'] =~ /^rex/
  false
end

def action(message: message)
  "*I am responding* _to_ @#{message['username']} in channel ##{message['channelname']}\n"
end

master = InstantSlackBot::Master.new(instabot_options)

my_bot = InstantSlackBot::Bot.new(
  conditions: method(:conditions),
  action: method(:action)
)

master << my_bot

master.run
